/**
 * External C# API surface for the C# resolver: types that live outside the repo —
 * the .NET Standard 2.1 BCL, the Unity engine/editor assemblies and package
 * sources — described just enough to type a member chain (`transform.parent`,
 * `GetComponent<T>()`) and to walk a base-class chain (`Selectable` →
 * `UIBehaviour` → `MonoBehaviour`).
 *
 * Data comes from two places:
 *   - `data/unity-api.json`, generated by `scripts/gen-unity-api.mjs` from the
 *     reference assemblies (ECMA-335 metadata) and XML docs of the installed
 *     editor, plus the MonoBehaviour/ScriptableObject/Editor message lists of the
 *     ScriptReference of the same Unity version. Committed, so a machine without
 *     Unity resolves identically.
 *   - {@link SEED}: a small hand-checked core, used when the generated file is
 *     absent (a source checkout before generation) and by unit tests.
 *
 * Type references inside the data are C#-shaped text with fully-qualified names:
 * `System.Collections.Generic.List<T>`, `T[]`; a method's own generic parameters
 * are `!!0`, `!!1` (the call's explicit type arguments).
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export interface ApiMember {
  /** Value/return type. */
  t: string;
  /** Methods: return type of the generic overload (`GetComponent<T>()` → `!!0`). */
  tg?: string;
  /** m = method, p = property, f = field, e = event, c = constant. */
  k: "m" | "p" | "f" | "e" | "c";
  s?: 1; // static
}

export interface ApiType {
  k: "class" | "struct" | "interface" | "enum" | "delegate";
  b?: string; // base class (FQN text)
  i?: string[]; // interfaces
  g?: string[]; // generic parameter names
  m?: Record<string, ApiMember>;
  v?: 1; // virtual/abstract members are listed in `vm`
  vm?: string[]; // names of overridable (virtual/abstract) members
}

export interface ApiData {
  /** Where it came from: editor version, generator, date. */
  source: string;
  /** "Namespace.Name`arity" (arity suffix only when generic) → type. */
  types: Record<string, ApiType>;
  /** Engine messages per receiving base class FQN: "UnityEngine.MonoBehaviour" → ["Awake", …]. */
  messages: Record<string, string[]>;
  /** Attribute type FQNs (without the `Attribute` suffix stripped). */
  attributes?: string[];
}

const T = "!!0";

/** Hand-checked core, enough for unit tests and for a checkout without the
 * generated data. Mirrors the generated format. */
export const SEED: ApiData = {
  source: "seed (hand-checked core of UnityEngine 6000.6 / .NET Standard 2.1)",
  types: {
    "System.Object": { k: "class", m: { ToString: { t: "System.String", k: "m" }, GetType: { t: "System.Type", k: "m" } } },
    "System.String": { k: "class", b: "System.Object", m: { Length: { t: "System.Int32", k: "p" } } },
    "System.Int32": { k: "struct" },
    "System.Single": { k: "struct" },
    "System.Boolean": { k: "struct" },
    "System.Void": { k: "struct" },
    "System.Type": { k: "class", b: "System.Object" },
    "System.Action": { k: "delegate" },
    "System.Action`1": { k: "delegate", g: ["T"] },
    "System.Func`1": { k: "delegate", g: ["TResult"] },
    "System.Func`2": { k: "delegate", g: ["T", "TResult"] },
    "System.Collections.Generic.IEnumerable`1": { k: "interface", g: ["T"] },
    "System.Collections.Generic.List`1": {
      k: "class",
      g: ["T"],
      i: ["System.Collections.Generic.IList<T>"],
      m: { Count: { t: "System.Int32", k: "p" }, Add: { t: "System.Void", k: "m" }, Find: { t: "T", k: "m" } },
    },
    "System.Collections.Generic.IList`1": { k: "interface", g: ["T"] },
    "System.Collections.Generic.Dictionary`2": {
      k: "class",
      g: ["TKey", "TValue"],
      m: {
        Count: { t: "System.Int32", k: "p" },
        Keys: { t: "System.Collections.Generic.IEnumerable<TKey>", k: "p" },
        Values: { t: "System.Collections.Generic.IEnumerable<TValue>", k: "p" },
      },
    },
    "System.Collections.Generic.KeyValuePair`2": {
      k: "struct",
      g: ["TKey", "TValue"],
      m: { Key: { t: "TKey", k: "p" }, Value: { t: "TValue", k: "p" } },
    },
    "System.Collections.Generic.HashSet`1": { k: "class", g: ["T"] },
    "System.Collections.Generic.Queue`1": { k: "class", g: ["T"], m: { Dequeue: { t: "T", k: "m" }, Peek: { t: "T", k: "m" } } },
    "System.Collections.Generic.Stack`1": { k: "class", g: ["T"], m: { Pop: { t: "T", k: "m" }, Peek: { t: "T", k: "m" } } },
    "System.Threading.Tasks.Task`1": { k: "class", g: ["TResult"], m: { Result: { t: "TResult", k: "p" } } },
    "System.Linq.Enumerable": { k: "class" },
    "UnityEngine.Object": {
      k: "class",
      b: "System.Object",
      m: {
        name: { t: "System.String", k: "p" },
        Instantiate: { t: T, k: "m", s: 1 },
        Destroy: { t: "System.Void", k: "m", s: 1 },
        FindObjectOfType: { t: T, k: "m", s: 1 },
        FindAnyObjectByType: { t: T, k: "m", s: 1 },
        FindFirstObjectByType: { t: T, k: "m", s: 1 },
        FindObjectsOfType: { t: "!!0[]", k: "m", s: 1 },
        FindObjectsByType: { t: "!!0[]", k: "m", s: 1 },
      },
    },
    "UnityEngine.Component": {
      k: "class",
      b: "UnityEngine.Object",
      m: {
        gameObject: { t: "UnityEngine.GameObject", k: "p" },
        transform: { t: "UnityEngine.Transform", k: "p" },
        tag: { t: "System.String", k: "p" },
        GetComponent: { t: T, k: "m" },
        GetComponentInChildren: { t: T, k: "m" },
        GetComponentInParent: { t: T, k: "m" },
        GetComponents: { t: "!!0[]", k: "m" },
        GetComponentsInChildren: { t: "!!0[]", k: "m" },
        GetComponentsInParent: { t: "!!0[]", k: "m" },
        TryGetComponent: { t: "System.Boolean", k: "m" },
        CompareTag: { t: "System.Boolean", k: "m" },
        SendMessage: { t: "System.Void", k: "m" },
        BroadcastMessage: { t: "System.Void", k: "m" },
      },
    },
    "UnityEngine.Behaviour": { k: "class", b: "UnityEngine.Component", m: { enabled: { t: "System.Boolean", k: "p" } } },
    "UnityEngine.MonoBehaviour": {
      k: "class",
      b: "UnityEngine.Behaviour",
      m: {
        StartCoroutine: { t: "UnityEngine.Coroutine", k: "m" },
        StopCoroutine: { t: "System.Void", k: "m" },
        Invoke: { t: "System.Void", k: "m" },
        InvokeRepeating: { t: "System.Void", k: "m" },
        CancelInvoke: { t: "System.Void", k: "m" },
      },
    },
    "UnityEngine.ScriptableObject": { k: "class", b: "UnityEngine.Object", m: { CreateInstance: { t: T, k: "m", s: 1 } } },
    "UnityEngine.StateMachineBehaviour": {
      k: "class",
      b: "UnityEngine.ScriptableObject",
      vm: ["OnStateEnter", "OnStateExit", "OnStateUpdate", "OnStateMove", "OnStateIK", "OnStateMachineEnter", "OnStateMachineExit"],
    },
    "UnityEngine.GameObject": {
      k: "class",
      b: "UnityEngine.Object",
      m: {
        transform: { t: "UnityEngine.Transform", k: "p" },
        tag: { t: "System.String", k: "p" },
        GetComponent: { t: T, k: "m" },
        GetComponentInChildren: { t: T, k: "m" },
        GetComponentInParent: { t: T, k: "m" },
        GetComponents: { t: "!!0[]", k: "m" },
        GetComponentsInChildren: { t: "!!0[]", k: "m" },
        AddComponent: { t: T, k: "m" },
        TryGetComponent: { t: "System.Boolean", k: "m" },
        SetActive: { t: "System.Void", k: "m" },
        Find: { t: "UnityEngine.GameObject", k: "m", s: 1 },
        FindWithTag: { t: "UnityEngine.GameObject", k: "m", s: 1 },
        CompareTag: { t: "System.Boolean", k: "m" },
      },
    },
    "UnityEngine.Transform": {
      k: "class",
      b: "UnityEngine.Component",
      m: {
        parent: { t: "UnityEngine.Transform", k: "p" },
        root: { t: "UnityEngine.Transform", k: "p" },
        Find: { t: "UnityEngine.Transform", k: "m" },
        GetChild: { t: "UnityEngine.Transform", k: "m" },
        position: { t: "UnityEngine.Vector3", k: "p" },
      },
    },
    "UnityEngine.Vector3": { k: "struct" },
    "UnityEngine.Coroutine": { k: "class" },
    "UnityEngine.Animator": {
      k: "class",
      b: "UnityEngine.Behaviour",
      m: {
        SetTrigger: { t: "System.Void", k: "m" },
        SetBool: { t: "System.Void", k: "m" },
        SetFloat: { t: "System.Void", k: "m" },
        SetInteger: { t: "System.Void", k: "m" },
        Play: { t: "System.Void", k: "m" },
        CrossFade: { t: "System.Void", k: "m" },
        StringToHash: { t: "System.Int32", k: "m", s: 1 },
      },
    },
    "UnityEngine.Renderer": {
      k: "class",
      b: "UnityEngine.Component",
      m: { material: { t: "UnityEngine.Material", k: "p" }, sharedMaterial: { t: "UnityEngine.Material", k: "p" } },
    },
    "UnityEngine.Material": {
      k: "class",
      b: "UnityEngine.Object",
      m: {
        shader: { t: "UnityEngine.Shader", k: "p" },
        SetFloat: { t: "System.Void", k: "m" },
        SetColor: { t: "System.Void", k: "m" },
        SetTexture: { t: "System.Void", k: "m" },
      },
    },
    "UnityEngine.Shader": { k: "class", b: "UnityEngine.Object", m: { Find: { t: "UnityEngine.Shader", k: "m", s: 1 }, PropertyToID: { t: "System.Int32", k: "m", s: 1 } } },
    "UnityEngine.Resources": { k: "class", m: { Load: { t: T, k: "m", s: 1 }, LoadAll: { t: "!!0[]", k: "m", s: 1 } } },
    "UnityEngine.Camera": { k: "class", b: "UnityEngine.Behaviour", m: { main: { t: "UnityEngine.Camera", k: "p", s: 1 } } },
    "UnityEngine.Time": { k: "class", m: { deltaTime: { t: "System.Single", k: "p", s: 1 } } },
    "UnityEngine.Debug": { k: "class", m: { Log: { t: "System.Void", k: "m", s: 1 } } },
    "UnityEngine.SerializeField": { k: "class" },
    "UnityEngine.DisallowMultipleComponent": { k: "class" },
    "UnityEngine.RuntimeInitializeOnLoadMethodAttribute": { k: "class" },
    "UnityEngine.ContextMenu": { k: "class" },
    "UnityEngine.SceneManagement.SceneManager": { k: "class", m: { LoadScene: { t: "System.Void", k: "m", s: 1 } } },
    "UnityEditor.Editor": { k: "class", b: "UnityEngine.ScriptableObject", vm: ["OnInspectorGUI", "OnSceneGUI", "OnEnable", "OnDisable", "CreateInspectorGUI"] },
    "UnityEditor.EditorWindow": { k: "class", b: "UnityEngine.ScriptableObject" },
    "UnityEditor.MenuItem": { k: "class" },
    "UnityEditor.InitializeOnLoadAttribute": { k: "class" },
    "UnityEditor.AssetPostprocessor": { k: "class" },
  },
  messages: {
    "UnityEngine.MonoBehaviour": [
      "Awake", "FixedUpdate", "LateUpdate", "OnAnimatorIK", "OnAnimatorMove", "OnApplicationFocus", "OnApplicationPause",
      "OnApplicationQuit", "OnAudioFilterRead", "OnBecameInvisible", "OnBecameVisible", "OnChildRectTransformDimensionsChange",
      "OnCollisionEnter", "OnCollisionEnter2D", "OnCollisionExit", "OnCollisionExit2D", "OnCollisionStay", "OnCollisionStay2D",
      "OnControllerColliderHit", "OnDestroy", "OnDisable", "OnDrawGizmos", "OnDrawGizmosSelected", "OnEnable", "OnGUI",
      "OnJointBreak", "OnJointBreak2D", "OnMouseDown", "OnMouseDrag", "OnMouseEnter", "OnMouseExit", "OnMouseOver", "OnMouseUp",
      "OnMouseUpAsButton", "OnParticleCollision", "OnParticleSystemStopped", "OnParticleTrigger", "OnParticleUpdateJobScheduled",
      "OnPostRender", "OnPreCull", "OnPreRender", "OnRenderImage", "OnRenderObject", "OnTransformChildrenChanged",
      "OnTransformParentChanged", "OnTriggerEnter", "OnTriggerEnter2D", "OnTriggerExit", "OnTriggerExit2D", "OnTriggerStay",
      "OnTriggerStay2D", "OnValidate", "OnWillRenderObject", "Reset", "Start", "Update",
    ],
    "UnityEngine.ScriptableObject": ["Awake", "OnDestroy", "OnDisable", "OnEnable", "OnValidate", "Reset"],
    "UnityEditor.EditorWindow": [
      "Awake", "CreateGUI", "OnBecameInvisible", "OnBecameVisible", "OnDestroy", "OnFocus", "OnGUI", "OnHierarchyChange",
      "OnInspectorUpdate", "OnLostFocus", "OnProjectChange", "OnSelectionChange", "Update",
    ],
    "UnityEditor.Editor": ["HasFrameBounds", "OnFrameBounds", "OnSceneGUI"],
  },
};

let loaded: ApiData | null = null;

/** The generated API data when present, else the seed. Read once per process. */
export function apiData(): ApiData {
  if (loaded) return loaded;
  const here = dirname(fileURLToPath(import.meta.url));
  for (const dir of [join(here, "data"), join(here, "..", "..", "src", "graph", "data")]) {
    try {
      const data = JSON.parse(readFileSync(join(dir, "unity-api.json"), "utf8")) as ApiData;
      // The seed stays authoritative for anything the generated data lacks.
      loaded = { ...data, types: { ...SEED.types, ...data.types }, messages: { ...SEED.messages, ...data.messages } };
      return loaded;
    } catch {
      /* try next */
    }
  }
  loaded = SEED;
  return loaded;
}

/** Test seam: replace the API data (null restores lazy loading). */
export function setApiDataForTest(data: ApiData | null): void {
  loaded = data;
}
